// scripts/data.js
// 這裡負責存放 ETF 的「假資料」

export const TIERS = ["rider", "operator", "keeper", "passenger"];

export const tierMeta = {
  rider: {
    title: "The Rider",
    subtitle: "乘勢加速｜順著趨勢往前衝",
  },
  operator: {
    title: "The Operator",
    subtitle: "主動管理｜策略調整與切換",
  },
  keeper: {
    title: "The Keeper",
    subtitle: "穩健守住｜以時間換取安心",
  },
  passenger: {
    title: "The Passenger",
    subtitle: "順勢搭乘｜把決策交給系統",
  },
};

export const etfList = [
  {
    id: "0050",
    tier: "passenger",
    name: "元大台灣50 (0050)",
    type: "指數型",
    image: "./assets/images/0050.png",
    selectionLogic: "追蹤台灣50大市值公司，依市值加權",
    industryWeights: {
      半導體: 0.45,
      電子零組件: 0.15,
      電腦周邊: 0.1,
      金融: 0.08,
      通訊: 0.07,
    },
    riskIndex: 3,
    growthIndex: 5,
    dividend: "1.5%~2%",
    description: "追蹤台灣前50大公司，代表台股整體市場。成長性佳、波動中等。",
  },
  {
    id: "00878",
    tier: "keeper",
    name: "國泰永續高股息 (00878)",
    type: "高股息＋永續",
    image: "./assets/images/00878.png",
    selectionLogic: "挑選ESG佳、配息穩定的企業組成",
    industryWeights: {
      半導體: 0.35,
      金融: 0.2,
      電子零組件: 0.1,
      科技硬體: 0.1,
      傳產: 0.08,
    },
    riskIndex: 2,
    growthIndex: 3,
    dividend: "4%~5%",
    description: "永續＋高息組合，穩定月月配息，適合想降低波動的小資族。",
  },
  {
    id: "0056",
    tier: "operator",
    name: "元大高股息 (0056)",
    type: "高股息",
    image: "./assets/images/0056.png",
    selectionLogic: "挑選預估未來一年股利殖利率最高的公司",
    industryWeights: {
      半導體: 0.25,
      電子零組件: 0.15,
      通訊設備: 0.1,
      金融: 0.1,
      其他電子: 0.08,
    },
    riskIndex: 3,
    growthIndex: 3,
    dividend: "4%~6%",
    description:
      "挑選預估未來最高股息的企業。息高但持股變動大，適合可承受波動者。",
  },
  {
    id: "006208",
    tier: "passenger",
    name: "富邦台50 (006208)",
    type: "指數型",
    image: "./assets/images/006208.png",
    selectionLogic: "追蹤台灣50大成分股，類似0050",
    industryWeights: {
      半導體: 0.45,
      電子零組件: 0.15,
      金融: 0.1,
      通訊: 0.08,
      電腦周邊: 0.08,
    },
    riskIndex: 3,
    growthIndex: 5,
    dividend: "1.5%~2%",
    description: "便宜版台灣50，追蹤大盤指數，適合長線投資。",
  },
  {
    id: "00919",
    tier: "operator",
    name: "群益台灣精選高息 (00919)",
    type: "高股息",
    image: "./assets/images/00919.png",
    selectionLogic: "依殖利率、成長、品質等多因子選股",
    industryWeights: {
      半導體: 0.4,
      電子零組件: 0.15,
      通訊: 0.1,
      科技硬體: 0.08,
      金融: 0.08,
    },
    riskIndex: 3,
    growthIndex: 4,
    dividend: "7%~8%",
    description: "熱門季配息ETF，科技比重高，息高成長也高。",
  },
  {
    id: "00713",
    tier: "keeper",
    name: "元大台灣高息低波 (00713)",
    type: "高股息＋低波動",
    image: "./assets/images/00713.png",
    selectionLogic: "挑選配息穩定且股價波動低的企業",
    industryWeights: {
      半導體: 0.3,
      金融: 0.2,
      通訊: 0.1,
      電子零組件: 0.1,
      傳產: 0.1,
    },
    riskIndex: 1,
    growthIndex: 2,
    dividend: "4%~5%",
    description: "低波動高息ETF，波動很小、領息穩定，適合保守型投資。",
  },
  {
    id: "00929",
    tier: "operator",
    name: "復華台灣科技優息 (00929)",
    type: "科技高股息",
    image: "./assets/images/00929.png",
    selectionLogic: "從科技150檔挑選高殖利率與品質佳公司",
    industryWeights: {
      半導體: 0.6,
      電子零組件: 0.2,
      電腦周邊: 0.1,
      通訊: 0.05,
      其他電子: 0.05,
    },
    riskIndex: 4,
    growthIndex: 5,
    dividend: "7%~8%",
    description: "極高科技比重，息高成長強，但波動偏大。",
  },
  {
    id: "00692",
    tier: "keeper",
    name: "富邦公司治理 (00692)",
    type: "公司治理型",
    image: "./assets/images/00692.png",
    selectionLogic: "挑選公司治理佳與財務健全的企業",
    industryWeights: {
      半導體: 0.3,
      金融: 0.2,
      電子零組件: 0.1,
      通訊: 0.1,
      傳產: 0.1,
    },
    riskIndex: 2,
    growthIndex: 3,
    dividend: "2%~3%",
    description: "挑選公司治理與財務穩健企業，走長期穩健路線。",
  },
  {
    id: "00881",
    tier: "rider",
    name: "國泰台灣科技龍頭 (00881)",
    type: "科技成長型",
    image: "./assets/images/00881.png",
    selectionLogic: "挑選台灣主要科技龍頭企業",
    industryWeights: {
      半導體: 0.65,
      電子零組件: 0.15,
      通訊: 0.1,
      電腦周邊: 0.05,
      其他電子: 0.05,
    },
    riskIndex: 4,
    growthIndex: 5,
    dividend: "1.5%~2.5%",
    description: "主攻科技龍頭，成長性高但波動較大。",
  },
  {
    id: "00757",
    tier: "rider",
    name: "統一FANG+ (00757)",
    type: "美國科技成長",
    image: "./assets/images/00757.png",
    selectionLogic: "追蹤FANG+指數，由10大美國科技巨頭組成",
    industryWeights: {
      網路服務: 0.35,
      雲端軟體: 0.3,
      電動車: 0.15,
      電子商務: 0.1,
      半導體: 0.1,
    },
    riskIndex: 5,
    growthIndex: 5,
    dividend: "0%~1%",
    description: "美國科技巨頭ETF，高波動高成長，適合進取型投資。",
  },
];
